const programsData = {
    Labs: [
        {
          title: 'Getting Started Lab For Employment Service Providers (ESP)',
          type: 'Public',
          lastUpdate: '1 year ago',
          members: 35,
          duration: 'None',
          level: 'None',
          description: "If you're here, then you're a passionate employment service provider who's constantly looking for new tools and concepts. We've prepared a series of Challenges just for you! The Challenges in the Lab are designed to help you learn how you can get the most out of our platform. Get started today!",
          imageUrl: 'https://source.unsplash.com/625x355/?programming',
        },
        {
          title: "Full Stack Web Development Lab",
          type: "Public",
          lastUpdate: "4 months ago",
          members: 25,
          duration: "8 weeks",
          level: "Intermediate",
          description:
            "Join our Full Stack Web Development Lab. Learn to build scalable and interactive web applications using frontend and backend technologies. Dive into frameworks like React, Node.js, and more.",
          imageUrl: "https://source.unsplash.com/625x355/?code",
        },
        {
          title: "Data Science Exploration Lab",
          type: "Public",
          lastUpdate: "6 months ago",
          members: 30,
          duration: "10 weeks",
          level: "Advanced",
          description:
            "Explore the world of Data Science in our dedicated lab. Work on real-world datasets, apply machine learning algorithms, and gain hands-on experience in data analysis and visualization.",
          imageUrl: "https://source.unsplash.com/625x355/?technology",
        },
        {
          title: "Cloud Computing Lab",
          type: "Private",
          lastUpdate: "8 months ago",
          members: 20,
          duration: "12 weeks",
          level: "Advanced",
          description:
            "Participate in our Cloud Computing Lab. Dive into cloud platforms such as AWS, Azure, or Google Cloud. Deploy and manage scalable applications in the cloud environment.",
          imageUrl: "https://source.unsplash.com/625x355/?development",
        },
        {
          title: "Mobile App Prototyping Lab",
          type: "Public",
          lastUpdate: "5 months ago",
          members: 15,
          duration: "6 weeks",
          level: "Beginner",
          description:
            "Learn mobile app prototyping in our lab. Use tools like Figma or Adobe XD to create interactive prototypes. Gain insights into user experience design for mobile applications.",
          imageUrl: "https://source.unsplash.com/625x355/?coding",
        },
        {
          title: "AI and Robotics Lab",
          type: "Private",
          lastUpdate: "7 months ago",
          members: 40,
          duration: "Ongoing",
          level: "Advanced",
          description:
            "Join the AI and Robotics Lab. Explore artificial intelligence, machine learning, and robotics. Work on projects that involve computer vision, natural language processing, and more.",
          imageUrl: "https://source.unsplash.com/625x355/?web",
        },
        {
          title: "Cybersecurity Simulation Lab",
          type: "Public",
          lastUpdate: "9 months ago",
          members: 18,
          duration: "8 weeks",
          level: "Intermediate",
          description:
            "Simulate real-world cyber threats in our lab. Learn ethical hacking, vulnerability assessment, and security best practices. Enhance your skills in protecting digital assets.",
          imageUrl: "https://source.unsplash.com/625x355/?software",
        },
        {
          title: "Quantum Computing Lab",
          type: "Public",
          lastUpdate: "10 months ago",
          members: 22,
          duration: "Ongoing",
          level: "Advanced",
          description:
            "Dive into the world of Quantum Computing. Explore quantum algorithms, quantum gates, and quantum programming. Contribute to cutting-edge research in quantum information science.",
          imageUrl: "https://source.unsplash.com/625x355/?developer",
        },
        {
          title: "Virtual Reality (VR) Lab",
          type: "Private",
          lastUpdate: "11 months ago",
          members: 35,
          duration: "10 weeks",
          level: "Intermediate",
          description:
            "Experience Virtual Reality in our lab. Develop immersive VR applications using platforms like Unity3D and Oculus. Explore the intersection of technology and virtual environments.",
          imageUrl: "https://source.unsplash.com/625x355/?computer",
        },
        {
          title: "Blockchain Development Lab",
          type: "Public",
          lastUpdate: "1 year ago",
          members: 28,
          duration: "12 weeks",
          level: "Intermediate",
          description:
            "Get hands-on experience in Blockchain Development. Explore smart contracts, decentralized applications (DApps), and blockchain consensus algorithms. Contribute to blockchain-based projects.",
          imageUrl: "https://source.unsplash.com/625x355/?javascript",
        },
        {
          title: "Natural Language Processing Lab",
          type: "Private",
          lastUpdate: "1 year ago",
          members: 19,
          duration: "8 weeks",
          level: "Advanced",
          description:
            "Join our Natural Language Processing (NLP) Lab. Work on projects involving text analysis, sentiment analysis, and language understanding. Explore the applications of NLP in various domains.",
          imageUrl: "https://source.unsplash.com/625x355/?html",
        },
        {
          title: "Internet of Things (IoT) Lab",
          type: "Public",
          lastUpdate: "1 year ago",
          members: 30,
          duration: "Ongoing",
          level: "Intermediate",
          description:
            "Explore the world of IoT in our dedicated lab. Build connected devices, experiment with IoT platforms, and develop solutions for real-world IoT applications.",
          imageUrl: "https://source.unsplash.com/625x355/?css",
        },
      ],
      Challenges: [
        {
          title: "Web Development Challenge Series",
          type: "Private",
          lastUpdate: "6 months ago",
          members: 20,
          duration: "3 weeks",
          level: "Intermediate",
          description: "Join our Web Development Challenge Series to enhance your coding skills and build real-world projects. This series covers a range of topics including frontend development, backend development, and more!",
          imageUrl: 'https://source.unsplash.com/625x355/?Web%20Development%20Challenge%20Series',
        },
        {
          title: "JavaScript Coding Challenge Series",
          type: "Public",
          lastUpdate: "3 months ago",
          members: 18,
          duration: "5 weeks",
          level: "Intermediate",
          description: "Join our JavaScript Coding Challenge Series. Sharpen your JavaScript skills through a series of challenges covering topics like algorithms, data structures, and advanced language features.",
          imageUrl: 'https://source.unsplash.com/625x355/?JavaScript%20Coding%20Challenge%20Series',
        },
        {
          title: "UI/UX Design Challenge: Redesign a Website",
          type: "Private",
          lastUpdate: "4 months ago",
          members: 25,
          duration: "6 weeks",
          level: "Intermediate",
          description: "Participate in our UI/UX Design Challenge. Redesign an existing website to improve user experience and visual appeal. Receive feedback from experienced designers and developers.",
          imageUrl: 'https://source.unsplash.com/625x355/?UI/UX%20Design%20Challenge:%20Redesign%20a%20Website',
        },
        {
          title: "Python Algorithmic Challenges",
          type: "Public",
          lastUpdate: "6 months ago",
          members: 30,
          duration: "8 weeks",
          level: "Advanced",
          description: "Take on Python Algorithmic Challenges. Solve complex problems using Python programming. Explore algorithms, dynamic programming, and advanced data structures.",
          imageUrl: 'https://source.unsplash.com/625x355/?Python%20Algorithmic%20Challenges',
        },
        {
          title: "Mobile App Development Challenge",
          type: "Public",
          lastUpdate: "7 months ago",
          members: 20,
          duration: "4 weeks",
          level: "Intermediate",
          description: "Challenge yourself with Mobile App Development. Build a functional mobile app with a specific set of features and requirements. Showcase your skills in app design and development.",
          imageUrl: 'https://source.unsplash.com/625x355/?Mobile%20App%20Development%20Challenge',
        },
        {
          title: "Cryptography Puzzle Challenge",
          type: "Private",
          lastUpdate: "8 months ago",
          members: 15,
          duration: "6 weeks",
          level: "Advanced",
          description: "Delve into the world of cryptography with our Puzzle Challenge. Solve cryptographic puzzles, crack codes, and understand the principles behind secure communication.",
          imageUrl: 'https://source.unsplash.com/625x355/?Cryptography%20Puzzle%20Challenge',
        },
        {
          title: "React.js Coding Challenge",
          type: "Public",
          lastUpdate: "9 months ago",
          members: 22,
          duration: "5 weeks",
          level: "Intermediate",
          description: "Improve your React.js skills through our coding challenge. Work on practical exercises and real-world scenarios to enhance your proficiency in building React applications.",
          imageUrl: 'https://source.unsplash.com/625x355/?React.js%20Coding%20Challenge',
        },
        {
          title: "Game Development Challenge: 2D Platformer",
          type: "Private",
          lastUpdate: "10 months ago",
          members: 28,
          duration: "8 weeks",
          level: "Intermediate",
          description: "Embark on a Game Development Challenge. Create a 2D platformer game using game development frameworks. Learn the fundamentals of game design, mechanics, and coding.",
          imageUrl: 'https://source.unsplash.com/625x355/?Game%20Development%20Challenge:%202D%20Platformer',
        },
        {
          title: "DevOps Challenge: CI/CD Pipeline",
          type: "Public",
          lastUpdate: "11 months ago",
          members: 35,
          duration: "6 weeks",
          level: "Advanced",
          description: "Take on our DevOps Challenge. Build a continuous integration and continuous deployment (CI/CD) pipeline. Learn about automation, version control, and deployment strategies.",
          imageUrl: 'https://source.unsplash.com/625x355/?DevOps%20Challenge:%20CI/CD%20Pipeline',
        },
        {
          title: "Angular Framework Challenge",
          type: "Public",
          lastUpdate: "1 year ago",
          members: 40,
          duration: "4 weeks",
          level: "Intermediate",
          description: "Challenge yourself with the Angular Framework. Develop a web application using Angular, explore component-based architecture, and implement advanced features.",
          imageUrl: 'https://source.unsplash.com/625x355/?Angular%20Framework%20Challenge',
        },
        {
          title: "Network Security Challenge",
          type: "Private",
          lastUpdate: "1 year ago",
          members: 18,
          duration: "Ongoing",
          level: "Advanced",
          description: "Join our Network Security Challenge. Simulate real-world security threats, implement countermeasures, and gain practical experience in securing computer networks.",
          imageUrl: 'https://source.unsplash.com/625x355/?Network%20Security%20Challenge',
        },
        {
          title: "Artificial Intelligence Challenge: Image Recognition",
          type: "Public",
          lastUpdate: "1 year ago",
          members: 25,
          duration: "8 weeks",
          level: "Advanced",
          description: "Participate in our AI Challenge. Develop an image recognition system using machine learning. Explore deep learning frameworks and algorithms for computer vision.",
          imageUrl: 'https://source.unsplash.com/625x355/?Artificial%20Intelligence%20Challenge:%20Image%20Recognition',
        },
      ],
      Resources: [
        {
          title: "Frontend Development Resources",
          type: "Public",
          lastUpdate: "2 months ago",
          members: 50,
          duration: "Self-paced",
          level: "All levels",
          description: "Explore a curated list of resources to master frontend development. From HTML and CSS to advanced JavaScript frameworks, these resources will help you build modern and responsive user interfaces.",
          imageUrl: 'https://source.unsplash.com/625x355/?Frontend%20Development%20Resources',
        },
        {
          title: "Web Development Guide: From Basics to Advanced",
          type: "Public",
          lastUpdate: "3 months ago",
          members: 18,
          duration: "Self-paced",
          level: "All Levels",
          description: "Explore our comprehensive Web Development Guide. Learn HTML, CSS, JavaScript, and advance to frameworks like React and Node.js. Perfect for beginners and those looking to enhance their skills.",
          imageUrl: 'https://source.unsplash.com/625x355/?Web%20Development%20Guide:%20From%20Basics%20to%20Advanced',
        },
        {
          title: "Machine Learning Tutorial Series",
          type: "Private",
          lastUpdate: "4 months ago",
          members: 25,
          duration: "Ongoing",
          level: "Intermediate",
          description: "Dive into the world of Machine Learning with our tutorial series. Covering key concepts, algorithms, and practical applications, this series is ideal for anyone interested in ML.",
          imageUrl: 'https://source.unsplash.com/625x355/?Machine%20Learning%20Tutorial%20Series',
        },
        {
          title: "JavaScript Frameworks Comparison",
          type: "Public",
          lastUpdate: "6 months ago",
          members: 30,
          duration: "1 week",
          level: "Intermediate",
          description: "Explore a detailed comparison of popular JavaScript frameworks. This resource provides insights into the features, advantages, and use cases of frameworks like React, Angular, and Vue.",
          imageUrl: 'https://source.unsplash.com/625x355/?JavaScript%20Frameworks%20Comparison',
        },
        {
          title: "Data Science Learning Path",
          type: "Public",
          lastUpdate: "7 months ago",
          members: 20,
          duration: "Self-paced",
          level: "Intermediate",
          description: "Follow our Data Science Learning Path. Covering topics from data preprocessing to machine learning, this resource guides you through the essential skills needed for a career in data science.",
          imageUrl: 'https://source.unsplash.com/625x355/?Data%20Science%20Learning%20Path',
        },
        {
          title: "Cybersecurity Best Practices Handbook",
          type: "Private",
          lastUpdate: "8 months ago",
          members: 15,
          duration: "Ongoing",
          level: "All Levels",
          description: "Access our Cybersecurity Best Practices Handbook. Learn essential security measures, secure coding practices, and strategies to protect against common cyber threats.",
          imageUrl: 'https://source.unsplash.com/625x355/?Cybersecurity%20Best%20Practices%20Handbook',
        },
        {
          title: "UI/UX Design Resources Collection",
          type: "Public",
          lastUpdate: "9 months ago",
          members: 22,
          duration: "Ongoing",
          level: "All Levels",
          description: "Explore our UI/UX Design Resources Collection. Curated articles, tutorials, and tools to enhance your skills in user interface and user experience design.",
          imageUrl: 'https://source.unsplash.com/625x355/?UI/UX%20Design%20Resources%20Collection',
        },
        {
          title: "Cloud Computing Basics Handbook",
          type: "Private",
          lastUpdate: "10 months ago",
          members: 28,
          duration: "Self-paced",
          level: "Beginner",
          description: "Learn the basics of Cloud Computing with our comprehensive handbook. Understand cloud services, deployment models, and key concepts in cloud computing.",
          imageUrl: 'https://source.unsplash.com/625x355/?Cloud%20Computing%20Basics%20Handbook',
        },
        {
          title: "Mobile App Development Resources",
          type: "Public",
          lastUpdate: "11 months ago",
          members: 35,
          duration: "Ongoing",
          level: "All Levels",
          description: "Access a wealth of resources for Mobile App Development. From design principles to coding practices, this collection supports aspiring and experienced mobile app developers.",
          imageUrl: 'https://source.unsplash.com/625x355/?Mobile%20App%20Development%20Resources',
        },
        {
          title: "Blockchain Technology Explained",
          type: "Public",
          lastUpdate: "1 year ago",
          members: 40,
          duration: "1 week",
          level: "Beginner",
          description: "Dive into the world of blockchain with our explanatory resource. Understand the fundamentals, key concepts, and real-world applications of blockchain technology.",
          imageUrl: 'https://source.unsplash.com/625x355/?Blockchain%20Technology%20Explained',
        },
        {
          title: "Artificial Intelligence Resources Hub",
          type: "Private",
          lastUpdate: "1 year ago",
          members: 18,
          duration: "Ongoing",
          level: "Intermediate",
          description: "Explore our AI Resources Hub. Curated articles, tutorials, and tools covering various aspects of artificial intelligence, including machine learning, natural language processing, and more.",
          imageUrl: 'https://source.unsplash.com/625x355/?Artificial%20Intelligence%20Resources%20Hub',
        },
        {
          title: "Networking Essentials Guide",
          type: "Public",
          lastUpdate: "1 year ago",
          members: 25,
          duration: "Self-paced",
          level: "Beginner",
          description: "Master the essentials of networking with our comprehensive guide. Learn about networking protocols, hardware, and troubleshooting techniques.",
          imageUrl: 'https://source.unsplash.com/625x355/?Networking%20Essentials%20Guide',
        },
      ],
      Projects: [
        {
          title: "Open Source Project: Community App",
          type: "Public",
          lastUpdate: "4 months ago",
          members: 100,
          duration: "Ongoing",
          level: "Advanced",
          description: "Contribute to our open-source Community App project! This project aims to build a platform for community engagement, and we welcome developers of all levels to contribute and learn together.",
          imageUrl: 'https://source.unsplash.com/625x355/?Open%20Source%20Project:%20Community%20App',
        },
        {
          title: "E-commerce Platform Redesign",
          type: "Private",
          lastUpdate: "3 months ago",
          members: 30,
          duration: "2 months",
          level: "Intermediate",
          description: "Join our team in redesigning an e-commerce platform. Enhance user experience, improve accessibility, and implement new features to create a more engaging shopping experience.",
          imageUrl: 'https://source.unsplash.com/625x355/?E-commerce%20Platform%20Redesign',
        },
        {
          title: "Mobile App Development: Task Manager",
          type: "Public",
          lastUpdate: "5 months ago",
          members: 40,
          duration: "4 weeks",
          level: "Beginner",
          description: "Learn mobile app development by working on a Task Manager app. This project covers basic app structure, data storage, and user interface design for both iOS and Android platforms.",
          imageUrl: 'https://source.unsplash.com/625x355/?Mobile%20App%20Development:%20Task%20Manager',
        },
        {
          title: "Machine Learning Showcase",
          type: "Public",
          lastUpdate: "6 months ago",
          members: 25,
          duration: "Ongoing",
          level: "Advanced",
          description: "Participate in our Machine Learning Showcase project. Explore various ML algorithms, work on real-world datasets, and showcase your results in a collaborative environment.",
          imageUrl: 'https://source.unsplash.com/625x355/?Machine%20Learning%20Showcase',
        },
        {
          title: "Community-driven Chat App",
          type: "Public",
          lastUpdate: "4 months ago",
          members: 60,
          duration: "3 months",
          level: "Intermediate",
          description: "Collaborate on building a community-driven chat application. Implement real-time features, user authentication, and create a seamless messaging experience for users.",
          imageUrl: 'https://source.unsplash.com/625x355/?Community-driven%20Chat%20App',
        },
        {
          title: "Data Visualization Dashboard",
          type: "Private",
          lastUpdate: "2 months ago",
          members: 20,
          duration: "6 weeks",
          level: "Advanced",
          description: "Work on a Data Visualization Dashboard project. Use D3.js or other visualization libraries to create interactive dashboards for displaying complex datasets.",
          imageUrl: 'https://source.unsplash.com/625x355/?Data%20Visualization%20Dashboard',
        },
        {
          title: "Cybersecurity Awareness Campaign",
          type: "Public",
          lastUpdate: "7 months ago",
          members: 45,
          duration: "Ongoing",
          level: "All levels",
          description: "Contribute to our Cybersecurity Awareness Campaign. Develop educational materials, interactive quizzes, and resources to raise awareness about online security.",
          imageUrl: 'https://source.unsplash.com/625x355/?Cybersecurity%20Awareness%20Campaign',
        },
        {
          title: "Augmented Reality (AR) Game",
          type: "Public",
          lastUpdate: "8 months ago",
          members: 35,
          duration: "10 weeks",
          level: "Intermediate",
          description: "Join the AR Game Development project. Create an immersive augmented reality game using ARKit, ARCore, or other AR development frameworks.",
          imageUrl: 'https://source.unsplash.com/625x355/?Augmented%20Reality%20(AR)%20Game',
        },
        {
          title: "Blockchain Voting System",
          type: "Private",
          lastUpdate: "1 year ago",
          members: 15,
          duration: "Ongoing",
          level: "Advanced",
          description: "Contribute to the development of a secure blockchain-based voting system. Explore the intersection of blockchain technology and electoral processes.",
          imageUrl: 'https://source.unsplash.com/625x355/?Blockchain%20Voting%20System',
        },
        {
          title: "Health and Fitness App",
          type: "Public",
          lastUpdate: "9 months ago",
          members: 50,
          duration: "4 months",
          level: "Intermediate",
          description: "Collaborate on a Health and Fitness App project. Implement features such as workout tracking, nutrition planning, and community challenges to promote a healthy lifestyle.",
          imageUrl: 'https://source.unsplash.com/625x355/?Health%20and%20Fitness%20App',
        },
        // ... (repeat for other projects)
      ],
};

export default programsData